# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "I+bbYUgY5Hi3zvXGbemHIVcKAF0yXxQKLB0uLGEnQwqjdZcxBYJpsLzj3SStuHCO2+5MI1IFM3jMtplYt08dIsLkmWST+Won5hGrutp4fESlJzaaFWeShULfymaJByuBbLjOi2PP1jvjGsI4MZRxgGauAO53HaNWiIGQJQ/RJd4aHKyIWjN4yVAnwfN/A8SA1mnEGvPoMpxB5LVOta1jwxKRWS8/dYyz+nZ++HpflGtGt+nPVio0EkSkQN5Ed4HhHJ8EtJlP2/lqmtmpQBlqwRUDNcVv4vKrgGiCeYhIqKqkdQo8Vtuvrrxtg8TVR/snmvRYtMuHFmg+j9DsECdp4cX1VBkT5uyynxx1m1t+MZZ6oeJwjNeR8a4CmwsIYC6SOoySPyd9jrcqN2uhlq4LdQQ86T9/JKt2BFsj9712iFg6RXTzGH8EHpyEEDNEfpgkP3qjJYApVzIlF6jPpGKNknGfnkAdT+ODloaZH7Pf+Trq42nAF2VLsdFehzwDiwq9P7s6c65DJHSs1NNiYF8eay27XTzZAwl3ioaM/aaMzUZSQSnA9VsiZ7StJjhYym1NqjfW0ZwDhpgF4mI4Ul2yrQXC5Mnh01MDUDklHQbjPKNcx+c9NgF5zZ9md1NyU/NVuS1xpaEMMdigICLME+aNLrydpRCHGa0RbAeVscXqz20="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi